server:
  port: 8068
spring:
  application:
    name: flywheel-web
  profiles:
    active: test

  # 配置数据库公共参数
  datasource:
    hikari:
      read-only: false
      connection-timeout: 30000
      idle-timeout: 30000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 60
      minimum-idle: 10
      auto-commit: true
      connection-test-query: SELECT 1

# DUBBO公共参数
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
  provider:
    timeout: 30000
    retries: 0


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


logging:
  config: classpath:logback-flywheel.xml